CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    user_name TEXT NOT NULL,
    user_password TEXT NOT NULL,
    user_bio TEXT,
    lowest_time TEXT,
    date_created TIMESTAMPTZ NOT NULL DEFAULT now()
);