CREATE TABLE friends (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    friend_name TEXT,
    friend_user_id INTEGER,
    user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    date_created TIMESTAMPTZ NOT NULL DEFAULT now()
);